### ISSUE TITLE
implement tracking

### ISSUE THREAD

**Issue by dominicbarnes** [dominicbarnes/pokemongo-tools#18]
- [x] user registered (identify)
 - [x] user login (identify)
 - [ ] user logout (reset)
 - [x] home (page)
 - [x] type chart (page)
 - [x] catalog (page)
 - [x] catalog view (page)
 - [x] catalog add (page)
 - [x] catalog filtered (track)
 - [x] catalog update (page)
 - [x] catalog evolve (track)
 - [x] catalog tm (track)
 - [x] catalog power up (track)
 - [x] catalog delete (track)
 - [x] pokedex (page)
 - [x] pokedex view (page)
 - [x] pokedex filtered (track)

I'll update this list as I think of more things.
